### ISSUE TITLE
Make more class like notice with font awesome

### ISSUE THREAD

**Issue by algui91** [algui91/algui91.github.io#1]
Make a few pre defined `notices` with, warning, info etc like

```css
.notice {
	margin-top: 1.5em;
	padding: .5em 1em;
	text-indent: 0;
	@include font-rem(14);
	background-color: $body-color;
	border: 1px solid darken($body-color,20);
	@include rounded(3px);
}

.notice:before {
	font-family: FontAwesome;
  content: "\f129";
  display: inline-block;
  padding-right: 3px;
  vertical-align: middle;
	font-size: 2em;
}
```
